### ISSUE TITLE
Counting/Selected Buildings Police and Fire Stations

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#105]
The Police Station and the Fire Station are marked as 'Unknown Building' when selected,
and thus will not showed in the building statics (not selected)
This is only affecting the New world Police and Fire Station

**Comment by StingMcRay** [comment]
Seams only affecting the Police Sttation

**Comment by FroggieFrog** [comment]
I will look into it.

**Comment by StingMcRay** [comment]
Yeah if you like to : my treatment is tomorrow so i can't type for a couple of days

**Comment by FroggieFrog** [comment]
I found the issue, but I haven't figured out why this code is present.
In the screenshot you see the relevant code and the issue as datatip.
Why is there a search via IconfileName? Why not just use the icon? There is no resizing of an icon as I can see.

![wrong_identifier](https://user-images.githubusercontent.com/6222752/58780992-e736be00-85da-11e9-8f54-00a4e9c0ecc0.png)

**Comment by StingMcRay** [comment]
I made this code that users when they create an own object that this will seen as 'Unknown Object' as this is not present in the preset list: i checked via IconName but then i think its something like I see the first (old world one) and that is not it, so it is unknown

**Comment by FroggieFrog** [comment]
This is also the root cause of another issue:
If you place the `Cattle Farm - (6)` from Obreros it should have the Identifier `Agriculture_colony01_09 (Cattle Farm)` but after line 517 it has Identifier `Agriculture_02 (Cattle Farm)`.
This is causing problems in the `FandomTemplateExporter` because now it is a completly different building (`Old World` vs `New World`).

**So I would suggest to remove this functionality completly for now till issue #106 is solved.**
