### ISSUE TITLE
No Influence information for Anno 2205 in the preset 3.5.1?

### ISSUE THREAD

**Issue by Corendiel** [AnnoDesigner/anno-designer#296]
Hello,

Am I missing something or the lastest preset does not contain any Influence information for Anno 2205?
I can see the radius on the other games but nothing for 2205.

Thanks in advance.

**Comment by StingMcRay** [comment]
Influence Range is never build in for 2205, as they not have that, and the system on 2205, was made and calculated on the houses connected to an building, so the range and fulfill of the building was fluctuating

**Comment by Corendiel** [comment]
I started the game recently with all the dlc and there are multiple buildings with Influence radius like the Institutes. The Arctic region depends on heating zone. Are you saying there is a lot of technology or other factors that increase or decrease the Influence radius?

**Comment by StingMcRay** [comment]
For the normal world it does
For aortic and moon yes,those has a steady value
But, we never intended or made or got this project to redo the whole Anno 2205 presets in terms of values / ranges / influence distances...
We have this project since Anno 1800, and we make this tool as good as we can for that game (and maybe if there will be a next Anno, who knows :)).... However we took the liberty to make  the presets so, that we supporting all Anno's (we took bits and peaces of the data reader to do this)

**Comment by Corendiel** [comment]
Ok so the values are just missing but technically we could add them to the preset. Looks like PickledWhispers who is mentioned on the about page created a preset but for an older version of Anno Designer version 7 available [here](https://mega.nz/#!Ox9SERRC!w-gR4f1vj6vuU5xCRljhy6yOPT49fv3VrSR-5wxqU3M). Some buildings are missing but a few radius values were in there. Is there a way I could help update the Preset? This tool loose a lot of it's interest if you don't have the Influence displayed.

**Comment by StingMcRay** [comment]
As we do the presets automatically it must be coded into the PresetParser.exe 
If you know where i need to look for those values (in the rda/assets.xml files what are a lot on 2205 lol) then i can see if we can use the same method that we now use in Anno 1800 presets. But that means we need to look into that, to see if we can make that into the presets, without harming the old layouts of 2205, as we took the code of that version (complete source code we have used since version 7) as well, ans made the 2205 part of the presets how it was then

**Comment by AgmasGold** [comment]
Yeah - the preset parser is currently just a separate project in the Anno Designer solution - but that's what you'd need to modify to extract the information, once the location of the information in the game files has been figured out.

**Comment by StingMcRay** [comment]
Yes :) i know lol, that is the project where i'm assigned on for 💯

**Comment by Corendiel** [comment]
I poked around the RDA files and for the life of me, I could not figure out how they define the radius value per building.

I looked at the code for the PresetParser and it looks like that feature is only supported for Anno 1800 and even for that game some values are hardcoded. The other games the value is just set to zero.

The Designer loses a lot of its value if you don't have the radius. Defining each value manually might be a pain but it might be the only option at this point.

**Comment by StingMcRay** [comment]
Well, if i have some time this weekend i will try to look into it to see what i can do for you but i do not promise anything, as  said, we have this project since 1800, and we work forward.... and we left the things as the where for the other anno's

**Comment by StingMcRay** [comment]
After Looking into the game, and its behavior i conclude that is has no sense to make this available for 2205, as i said before there is no use of Radius nor a steady Influence Distances.

* Productions buildings and its fields can be laid down in whatever direction, as long the fields (or modules) are connected to the main production building, its module or an other connected field.

* For Public buildings counts the number of houses connected to 1 public building, as is as follow : 
If you put 1 house on a long distance of the public building it will have the public building "in range" (picture 1), when i build more house then that long distance house will lose the public building (Picture 2)

Picture 1 
![afbeelding](https://user-images.githubusercontent.com/18048706/94361862-aad47e80-00b7-11eb-8a7a-f7c04a3f20ec.png)
Picture 2 
![afbeelding](https://user-images.githubusercontent.com/18048706/94361888-c8a1e380-00b7-11eb-8d26-a4640b747329.png)

As you see, it fluctuates and this counts for ALL Public Buildings  on each region (Earth, Tundra, Arctic and Moon)

_If you think you know, or have a building in 2205 that acts otherwise then i say above, then make a screenshot, tell what building it is, and how you think it works according your findings._

**Comment by Corendiel** [comment]
> there is no use of Radius nor a steady Influence Distances.

What about all the building generating heat in the arctic region and the shields in space? Optimizing these regions is a lot harder than the temperate zone.
![image](https://user-images.githubusercontent.com/1401010/94381424-4f31e180-0107-11eb-9b52-8a34679125ae.png)

Yes, public buildings don't have a radius but other types of buildings do. The Institutes for example use one.
![image](https://user-images.githubusercontent.com/1401010/94381467-7ee0e980-0107-11eb-91fe-76e1b5299c6d.png)

If the number of buildings is limited fixing these values manually should not take too long.

**Comment by StingMcRay** [comment]
The heat generation, that is arctic only, i can look into that, however the Anno Designer Tool is not made to show it the way it is on 2205 Arctic, you will see all circles then (like the Trade Union in Anno 1800)

What the Space station consider, that is a manual adding, but if that is a number it should be in the files

**Comment by StingMcRay** [comment]
Oke : Update : 
For arctic buildings i can add the ranges of it, but as i told before it will be done in the existing format of the presets, and will be set under the "InfluenceRadius" setting.

Code found, as example i used the data of the Pharma Lab
```
                       <ShieldGenerator>
                          <ShieldedRadius>12</ShieldedRadius>
                        </ShieldGenerator>  
```
and its field : 
```
                       <ShieldGenerator>
                          <ShieldedRadius>11</ShieldedRadius>
                        </ShieldGenerator>
```
So, that will workable then only it will be showed in AnnoDesigner like this : 
![afbeelding](https://user-images.githubusercontent.com/18048706/94542125-b4412080-0248-11eb-923b-e51383dffa47.png)
If you select all buildings, or switch on the `Show Influences` 
So a lot of drawings of circles will be there...

**Comment by Corendiel** [comment]
> Oke : Update :
> For arctic buildings i can add the ranges of it, but as i told before it will be done in the existing format of the presets, and will be set under the "InfluenceRadius" setting.
> 
> Code found, as example i used the data of the Pharma Lab
> 
> ```
>                        <ShieldGenerator>
>                           <ShieldedRadius>12</ShieldedRadius>
>                         </ShieldGenerator>  
> ```
> 
> and its field :
> 
> ```
>                        <ShieldGenerator>
>                           <ShieldedRadius>11</ShieldedRadius>
>                         </ShieldGenerator>
> ```
> 
> So, that will workable then only it will be showed in AnnoDesigner like this :
> ![afbeelding](https://user-images.githubusercontent.com/18048706/94542125-b4412080-0248-11eb-923b-e51383dffa47.png)
> If you select all buildings, or switch on the `Show Influences`
> So a lot of drawings of circles will be there...

Great that's all I was hoping for. Yes, shield and heat behave differently than influence but it's good enough for an old game. If you can add the two shields generator for the moon and the Institute buildings that would be perfect.

**Comment by StingMcRay** [comment]
`The institute ones are already in, i will search tomorrow for the Moon shield Generators

**Comment by StingMcRay** [comment]
Update : Pending Merge, and then the new presets.json will be available with the Anno 2205 radius objects
-> Radius to the Arctic buildings, for Heat Shield Generator, if exists
-> Radius to the Moon Protection Shield Generators
-> Radius to Training Center Buildings (Orbit DLC)

> After release, this issue will be closed

**Comment by StingMcRay** [comment]
Presets 3.6 is released, so topic will be closed

**Comment by Corendiel** [comment]
Thanks a lot

**Comment by StingMcRay** [comment]
Your welcome. It was a small thing to add finely :D
